// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb8dp7aLo8VHBhAAIIm865yUrw-fG7Z98',
    appId: '1:10314181716:web:bfcb2e2cbabfe1d35e11c1',
    messagingSenderId: '10314181716',
    projectId: 'ai-quanlichitieucanhan',
    authDomain: 'ai-quanlichitieucanhan.firebaseapp.com',
    storageBucket: 'ai-quanlichitieucanhan.firebasestorage.app',
    measurementId: 'G-V65C69LLN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS7Qx_3FEijEWndH6x_icXfHBAQm3qyBc',
    appId: '1:10314181716:android:e294747ffb4d90ad5e11c1',
    messagingSenderId: '10314181716',
    projectId: 'ai-quanlichitieucanhan',
    storageBucket: 'ai-quanlichitieucanhan.firebasestorage.app',
  );

}